import Head from 'next/head'
import Image from 'next/image'
import BlockExplorer from '../components/BlockExplorer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Block Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>

        </h1>

        <BlockExplorer />
      </main>
    </div>
  )
}
